### =========================================
### BASE CONFIG
### =========================================
@baseUrl = http://localhost:5000
@contentType = application/json


### =========================================
### 1️⃣ SIGNUP (Create Tenant + Admin)
### =========================================
POST {{baseUrl}}/auth/signup
Content-Type: {{contentType}}

{
  "shopName": "Ali Electronics",
  "OwnerName": "Ali",
  "currency": "PKR",
  "taxRate": 15,
  "email": "admin@ahli.com",
  "password": "password123"
}


### =========================================
### 2️⃣ LOGIN
### =========================================
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "alirashid2020e@gmail.com",
  "password": "123456"
}


### =========================================
### 3️⃣ SAVE TOKEN (PASTE AFTER LOGIN)
### =========================================
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbW0zN3pxaDYwMDAxMXd2YmI5cTBrM3M3IiwibmFtZSI6ImFsaSIsImVtYWlsIjoiYWxpcmFzaGlkMjAyMGVAZ21haWwuY29tIiwidGVuYW50SWQiOiJjbW0zN3pxYWEwMDAwMXd2Ymoxd2hpamNvIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzcyMTg2ODc4LCJleHAiOjE3NzIxODc3Nzh9.0yztkYoowIBMgH7NZ6LBdzTUDiNKSrsf9JqgsbeFL_k


### =========================================
### 4️⃣ REFRESH TOKEN
### =========================================
POST {{baseUrl}}/auth/refresh
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbW0zN3pxaDYwMDAxMXd2YmI5cTBrM3M3IiwibmFtZSI6ImFsaSIsImVtYWlsIjoiYWxpcmFzaGlkMjAyMGVAZ21haWwuY29tIiwidGVuYW50SWQiOiJjbW0zN3pxYWEwMDAwMXd2Ymoxd2hpamNvIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzcyMTg2ODc4LCJleHAiOjE3NzI3OTE2Nzh9.taz3ywFsgo17opXvoyGamw5PiQDB28hEKUzQEqNqClQ"
}


### =========================================
### 5️⃣ LOGOUT
### =========================================
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{token}}


### =========================================
### 6️⃣ GET CURRENT USER
### =========================================
GET {{baseUrl}}/auth/me
Authorization: Bearer {{token}}


#################################################
############## CATEGORIES MODULE ################
#################################################

### =========================================
### 5️⃣ CREATE CATEGORY
### =========================================
POST {{baseUrl}}/categories
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "name": "moblile"
}


### =========================================
### 6️⃣ GET ALL CATEGORIES
### =========================================
GET {{baseUrl}}/categories
Authorization: Bearer {{token}}


### =========================================
### 7️⃣ GET CATEGORY BY ID
### =========================================
GET {{baseUrl}}/categories/cmllzc0up0003b0vb2bk21ptb
Authorization: Bearer {{token}}


### =========================================
### 8️⃣ UPDATE CATEGORY
### =========================================
PATCH {{baseUrl}}/categories/cmllzc0up0003b0vb2bk21ptb
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "name": "moblile"
}


### =========================================
### 9️⃣ DELETE CATEGORY
### =========================================
DELETE {{baseUrl}}/categories/cmllz7coy0000b0vbst1ua94i
Authorization: Bearer {{token}}


#################################################
############## PRODUCTS MODULE ##################
#################################################

### =========================================
### 🔟 CREATE PRODUCT
### =========================================
POST {{baseUrl}}/products
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "name": "Laptop",
  "sku": "LAP-1002",
  "price": 150000,
  "cost": 120000,
  "stock": 10,
  "categoryId": "cmllzc0up0003b0vb2bk21ptb"
}


### =========================================
### 1️⃣1️⃣ GET ALL PRODUCTS
### =========================================
GET {{baseUrl}}/products
Authorization: Bearer {{token}}


### =========================================
### 1️⃣2️⃣ GET PRODUCT BY ID
### =========================================
GET {{baseUrl}}/products/cmllzsmno0000b0vbdc7g52wq
Authorization: Bearer {{token}}


### =========================================
### 1️⃣3️⃣ UPDATE PRODUCT
### =========================================
PATCH {{baseUrl}}/products/cmllzsmno0000b0vbdc7g52wq
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "name": "Updated Laptop",
  "price": 155000,
  "stock": 8
}


### =========================================
### 1️⃣4️⃣ DELETE PRODUCT
### =========================================
DELETE {{baseUrl}}/products/cmllzsmno0000b0vbdc7g52wq
Authorization: Bearer {{token}}

#################################################
############## SALES MODULE #####################
#################################################

###=========================================
###1️⃣ CREATE SALE (POST /sales)
###=========================================

POST {{baseUrl}}/sales
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "items": [
    { "productId": "cmlm20n0m0001a4vbrftzfcpo", "quantity": 2 },
    { "productId": "cmlm0teou0001b0vbc6cz7czv", "quantity": 1 }
  ],
  "paymentMethod": "CASH",
  "discountPercent": 5
}



####=========================================
###2️⃣ GET ALL SALES HISTORY (GET /sales)
###=========================================

GET {{baseUrl}}/sales
Authorization: Bearer {{token}}

###=========================================
###3️⃣ GET SALE BY ID (GET /sales/:id)
###=========================================

GET {{baseUrl}}/sales/cmlm33kt70003twvbko98ojgi
Authorization: Bearer {{token}}

#################################################
############## DASHBOARD MODULE ################
#################################################

###=========================================
###1️⃣ GET DASHBOARD METRICS (GET /dashboard/metrics)
####=========================================

GET {{baseUrl}}/dashboard/metrics
Authorization: Bearer {{token}}

###=========================================
###2️⃣ GET TOP SELLING PRODUCTS (GET /dashboard/top-selling)
###=========================================

GET {{baseUrl}}/dashboard/top-selling
Authorization: Bearer {{token}}

###=========================================
###3️⃣ GET LOW STOCK PRODUCTS (GET /dashboard/low-stock)
###=========================================

GET {{baseUrl}}/dashboard/low-stock
Authorization: Bearer {{token}}

#################################################
############## SUBSCRIPTIONS MODULE ############
#################################################

###=========================================
###1️⃣ SUBSCRIBE OR UPDATE PLAN (POST /subscriptions/subscribe)
###=========================================

POST {{baseUrl}}/subscriptions/subscribe
Content-Type: {{contentType}}
Authorization: Bearer {{token}}





###=========================================
###2️⃣ GET CURRENT SUBSCRIPTION STATUS (GET /subscriptions/status)
###=========================================

GET {{baseUrl}}/subscriptions/status
Authorization: Bearer {{token}}

#################################################
############## SALES INVOICE ###################
#################################################

###=========================================
###1️⃣ DOWNLOAD SALE INVOICE (GET /sales/:id/invoice)
###=========================================

GET {{baseUrl}}/sales/cmlm33kt70003twvbko98ojgi/invoice
Authorization: Bearer {{token}}