### =========================================
### BASE URL
### =========================================

@baseUrl = http://localhost:3000
@contentType = application/json


### =========================================
### 1️⃣ SIGNUP (Create Tenant + Admin)
### =========================================

POST {{baseUrl}}/auth/signup
Content-Type: {{contentType}}

{
  "shopName": "Ali Electronics",
  "OwnerName": "new admin",
  "currency": "PKR",
  "taxRate": 15,
  "email": "admin@alilctrnics.com",
  "password": "password123"
}


### =========================================
### 2️⃣ LOGIN
### =========================================

POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "admin@alilctrnics.com",
  "password": "password123"
}


### =========================================
### 3️⃣ SAVE TOKEN (MANUAL)
### After login, copy accessToken and paste below
### =========================================

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWxsbDI5YmMwMDAxOXd2YmNybDBua2pwIiwidGVuYW50SWQiOiJjbWxsbDI5NGgwMDAwOXd2YmFieGlvY2FtIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzcxMDMwODU3LCJleHAiOjE3NzEwMzA4NTh9.8XLDGG8nI26bkNOBYs6JNpnFmNV3GBVyZcAtZQAPIlE


### =========================================
### 4️⃣ GET CURRENT USER
### =========================================

GET {{baseUrl}}/auth/me
Authorization: Bearer {{token}}


### =========================================
### 5️⃣ TEST PROTECTED ROUTE (Example)
### =========================================

GET {{baseUrl}}/products
Authorization: Bearer {{token}}
